[package]
edition = "2021"
name = "basic-async"
version = "0.1.0"
publish = false

[dependencies]
# Clorinde
clorinde = { path = "basic_async_codegen", package = "basic_async_codegen" }
# Async
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
